name: Rectify11

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
    - name: Restore NuGet Packages
      run: nuget restore Rectify11Installer.sln
    - name: Build
      run: msbuild Rectify11Installer.sln /p:Configuration=Release /p:platform=x64
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        # Artifact name
        name: SkibidiDopDopDopDopYesYesYesYes11Installer-amd64
        # A file, directory or wildcard pattern that describes what to upload
        path: Rectify11Installer\bin\Release
